### ISSUE TITLE
Doesn't Work Sometimes

### ISSUE THREAD

**Issue by TheSacredWolf** [tadwohlrapp/disable-youtube-autoplay#1]
I'd say 70% of the time this doesn't turn auto play off. One time it either turned itself off or uninstalled itself.

**Comment by tadwohlrapp** [comment]
Thanks for the feedback, @TheSacredWolf!

You're right, the script was a bit unreliable from time to time.

I just updated it after tinkering around with various different approaches.

I'd love to hear from you again if this most recent update (v0.2.0) improved the reliability for you.

**Comment by TheSacredWolf** [comment]
I updated it and I've been using it throughout the day. It has been working every time. Thanks.
